"""Uploading a recording instead of a transcript.

The most obvious thing a user tries is dropping in the meeting recording.
Until now that failed with "must be UTF-8 text", which reads like the app
is broken rather than like the format is unsupported.

The interesting part is not the plumbing, it is what happens to speaker
attribution. Whisper returns words, not who said them, so a transcribed
recording starts fully unattributed — and unattributed speech cannot own
an action item. These tests pin that the pipeline stays honest about it:
blocked until a human says who spoke, approvable afterwards.
"""
import shutil
import subprocess

import pytest

pytestmark = pytest.mark.skipif(
    shutil.which("ffmpeg") is None, reason="ffmpeg is required to decode media"
)


@pytest.fixture(scope="module")
def wav_bytes(tmp_path_factory) -> bytes:
    """A real WAV, generated by ffmpeg rather than hand-assembled.

    A fake header would test our parsing of a file ffmpeg never has to
    read, which is precisely the part that breaks in the wild.
    """
    path = tmp_path_factory.mktemp("media") / "tone.wav"
    subprocess.run(
        ["ffmpeg", "-y", "-f", "lavfi", "-i", "sine=frequency=440:duration=6",
         "-ac", "1", "-ar", "16000", str(path)],
        capture_output=True, check=True,
    )
    return path.read_bytes()


@pytest.fixture(scope="module")
def mp4_bytes(tmp_path_factory) -> bytes:
    path = tmp_path_factory.mktemp("media") / "clip.mp4"
    subprocess.run(
        ["ffmpeg", "-y",
         "-f", "lavfi", "-i", "sine=frequency=440:duration=6",
         "-f", "lavfi", "-i", "color=c=blue:s=320x240:d=6",
         "-shortest", "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", str(path)],
        capture_output=True, check=True,
    )
    return path.read_bytes()


SPOKEN = (
    "Rohit, can you finish the API migration by Friday? "
    "Yes, I will finish the API migration by Friday."
)


@pytest.fixture(autouse=True)
def scripted_speech(transcriber):
    """Stock the scripted transcriber.

    Media ingestion transcribes one chunk at a time on the ``mic`` track,
    so each chunk consumes one queued line. Ten is far more than any test
    here needs and keeps the fixture from being a per-test chore.
    """
    for _ in range(10):
        transcriber.queue("mic", SPOKEN)
    return transcriber


def _upload(client, name: str, data: bytes, mime: str):
    return client.post(
        "/meetings",
        files={"file": (name, data, mime)},
        data={
            "title": "Recorded standup",
            "meeting_date": "2026-08-06",
            "participants": "Arjun\nRohit\nMeera",
        },
    )


# --- the formats ----------------------------------------------------------


def test_audio_is_transcribed_into_a_meeting(client, wav_bytes):
    response = _upload(client, "standup.wav", wav_bytes, "audio/wav")
    assert response.status_code == 200, response.text

    body = response.json()
    assert body["segments"] > 0
    assert body["source"] != "transcript", "the STT engine should be named"


def test_video_audio_is_extracted_and_transcribed(client, mp4_bytes):
    """Video is the same path with the picture discarded, so this mostly
    proves ffmpeg is actually being asked to demux."""
    response = _upload(client, "standup.mp4", mp4_bytes, "video/mp4")
    assert response.status_code == 200, response.text
    assert response.json()["segments"] > 0


def test_an_unsupported_format_says_what_is_supported(client):
    response = _upload(client, "notes.pages", b"\x00\x01\x02" * 100, "application/octet-stream")

    assert response.status_code == 400
    detail = response.json()["detail"]
    assert ".txt" in detail and ".mp4" in detail, detail


def test_a_recording_over_the_limit_is_refused_by_size_not_by_parsing(client):
    response = _upload(client, "huge.mp3", b"\x00" * (501 * 1024 * 1024), "audio/mpeg")
    assert response.status_code == 413
    assert "500MB" in response.json()["detail"]


def test_a_file_with_no_audio_track_says_so(client):
    response = _upload(client, "broken.wav", b"RIFF\x24\x00\x00\x00WAVE", "audio/wav")
    assert response.status_code == 422
    assert "No audio could be read" in response.json()["detail"]


# --- attribution ----------------------------------------------------------


def test_transcribed_speech_starts_unattributed(client, wav_bytes):
    """The whole safety story for uploaded media rests on this."""
    meeting_id = _upload(client, "standup.wav", wav_bytes, "audio/wav").json()["meeting_id"]

    transcript = client.get(f"/meetings/{meeting_id}/transcript").json()
    speakers = {s["speaker"] for s in transcript["segments"]}
    assert speakers == {"Unknown speaker"}


def test_nothing_from_an_untagged_recording_can_be_approved(client, wav_bytes):
    meeting_id = _upload(client, "standup.wav", wav_bytes, "audio/wav").json()["meeting_id"]
    detail = client.get(f"/meetings/{meeting_id}").json()

    assert all(not c["gate"]["eligible"] for c in detail["candidates"]), (
        "unattributed speech must not produce approvable work"
    )


def test_tagging_speakers_unlocks_the_commitment(client, wav_bytes):
    meeting_id = _upload(client, "standup.wav", wav_bytes, "audio/wav").json()["meeting_id"]
    detail = client.get(f"/meetings/{meeting_id}").json()
    participants = {p["name"]: p["participant_id"] for p in detail["participants"]}
    segments = client.get(f"/meetings/{meeting_id}/transcript").json()["segments"]

    response = client.post(
        f"/meetings/{meeting_id}/speakers",
        json={
            "assignments": {
                segments[0]["segment_id"]: participants["Arjun"],
                segments[1]["segment_id"]: participants["Rohit"],
            },
            "reanalyze": True,
        },
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["segments_updated"] == 2
    assert body["reanalysed"] is True

    after = client.get(f"/meetings/{meeting_id}").json()
    assert any(c["gate"]["eligible"] for c in after["candidates"]), (
        "tagging the owner should let at least one item through the gate"
    )
    assert any(c["owner_name"] == "Rohit" for c in after["candidates"])


def test_relabelling_a_whole_speaker_works_in_one_call(client, wav_bytes):
    """Clicking every segment individually would be unusable on a
    45-minute recording."""
    meeting_id = _upload(client, "standup.wav", wav_bytes, "audio/wav").json()["meeting_id"]
    detail = client.get(f"/meetings/{meeting_id}").json()
    participants = {p["name"]: p["participant_id"] for p in detail["participants"]}

    response = client.post(
        f"/meetings/{meeting_id}/speakers",
        json={"relabel": {"Unknown speaker": participants["Arjun"]}, "reanalyze": False},
    )
    assert response.json()["segments_updated"] >= 2

    speakers = {
        s["speaker"] for s in client.get(f"/meetings/{meeting_id}/transcript").json()["segments"]
    }
    assert speakers == {"Arjun"}


def test_speakers_can_only_be_set_to_real_participants(client, wav_bytes):
    """Otherwise attribution could name someone who was never in the room."""
    meeting_id = _upload(client, "standup.wav", wav_bytes, "audio/wav").json()["meeting_id"]

    response = client.post(
        f"/meetings/{meeting_id}/speakers",
        json={"relabel": {"Unknown speaker": "p-nobody"}},
    )
    assert response.status_code == 400
    assert "unknown participant" in response.json()["detail"]


def test_tagging_is_written_to_the_audit_log(client, wav_bytes):
    meeting_id = _upload(client, "standup.wav", wav_bytes, "audio/wav").json()["meeting_id"]
    detail = client.get(f"/meetings/{meeting_id}").json()
    participants = {p["name"]: p["participant_id"] for p in detail["participants"]}

    client.post(
        f"/meetings/{meeting_id}/speakers",
        json={"relabel": {"Unknown speaker": participants["Arjun"]}, "reviewer": "vyas"},
    )

    events = client.get(f"/review/meetings/{meeting_id}/audit").json()
    tagged = next(e for e in events if e["payload"].get("event") == "speakers_assigned")
    assert tagged["payload"]["reviewer"] == "vyas"


def test_reanalysis_refuses_once_something_has_been_reviewed(client, wav_bytes, tracker):
    """Re-extracting would orphan the decision or re-create actioned work."""
    meeting_id = _upload(client, "standup.wav", wav_bytes, "audio/wav").json()["meeting_id"]
    detail = client.get(f"/meetings/{meeting_id}").json()
    participants = {p["name"]: p["participant_id"] for p in detail["participants"]}
    segments = client.get(f"/meetings/{meeting_id}/transcript").json()["segments"]

    client.post(
        f"/meetings/{meeting_id}/speakers",
        json={
            "assignments": {
                segments[0]["segment_id"]: participants["Arjun"],
                segments[1]["segment_id"]: participants["Rohit"],
            }
        },
    )
    eligible = [
        c for c in client.get(f"/meetings/{meeting_id}").json()["candidates"]
        if c["gate"]["eligible"]
    ]
    assert eligible
    client.post(
        f"/review/candidates/{eligible[0]['candidate_id']}/approve",
        json={"reviewer": "vyas", "effects": ["github_issue"]},
    )
    created_before = len(tracker.created)

    response = client.post(
        f"/meetings/{meeting_id}/speakers",
        json={"relabel": {"Rohit": participants["Meera"]}, "reanalyze": True},
    )

    assert response.status_code == 200
    assert response.json()["reanalysed"] is False
    assert "already been reviewed" in " ".join(response.json()["warnings"])
    assert len(tracker.created) == created_before, "nothing may be re-created"
